version: '3.1'

services:
  pgadmin:
    build:
      context: .
      dockerfile: pgadmin.dockerfile
    depends_on:
      - postgres
    ports:
      - 80:80

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
